ALTER TABLE users ADD COLUMN email VARCHAR(255) DEFAULT NULL AFTER username;
ALTER TABLE users ADD COLUMN contact_no VARCHAR(50) DEFAULT NULL AFTER email;
ALTER TABLE users ADD COLUMN color_code VARCHAR(20) DEFAULT '#4285F4' AFTER contact_no;
